### PR TITLE
Metal Pagination Branch3

### PR DESCRIPTION
**Pull request by zsagia**
Hi Maira,

I'm sending you my third and fixed version of Pagination implementation. You were right in everything what you mentioned in the previous pull. I hope I could fix them correctly.

Thanks again for your detailed description and help,
 Zsaga

### CODE REVIEW

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mairatma** [comment]
Thanks a lot for this @zsagia! :D
Just letting you know, I've just added 2 very minor commits after merging your changes, the first just removing a "@method" from a doc block (we don't use those on Metal.js) and the other was just after running `gulp format`, which is a task we have for keeping the formatting standards. These were really minor things, so I didn't want you have to pass over to again just for that, but I'm letting you know, specially about the task so you can use it later :)

**Comment by zsagia** [comment]
No problem and I am very happy about this merge.

Thanks again.
2016. máj. 2. du. 9:07 ezt írta ("Maira Bello" notifications@github.com):

**Comment by mairatma** [comment]
Me too :D

**Pull request merged**
